apiVersion: v1  
kind: LimitRange  
metadata:  
  name: mem-limit-range
spec:  
  limits:  
  - default:  
      memory: 512Mi  
      cpu: "10m"
    defaultRequest:  
      memory: 256Mi  
    type: Container