apiVersion: v1
kind: Pod
metadata:
  name: guaranted
spec:
  containers:
  - name: qos
    image: nginx
    resources:
      limits:
        memory: "20Mi"
        cpu: "70m"
      requests:
        memory: "20Mi"
        cpu: "70m"