apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:php7.4
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: "mysql"
          - name: WORDPRESS_DB_USER
            value: "user"
          - name: WORDPRESS_DB_PASSWORD
            value: "password"
          - name: WORDPRESS_DB_NAME
            value: "cms"
          - name: WORDPRESS_DEBUG
            value: "1"